package emperatriz.fluviatilis.themes

data class Theme (
        var fluvHeight:Int,
        val fluvNumber: Int,
        var fluvWeight: Int,
        val speed:Int,
        var wideness:Int,
        var heightness:Int,
        val dimAlpha:Int,
        var dimHeight:Int,
        val rotation:Int,
        var horizontalOffset:Int,
        var verticalOffset:Int,
        val color:Int,
        val colorLeft:Int,
        val colorRight:Int,
        val widgetSelected:Int,
        val widgetX:Int?,
        val widgetY:Int?,
        val widgetXsize:Int?,
        val style:Int?,
        val discreto:Boolean?,
        val halo:Boolean?,
        val colorW1:Int?,
        val colorW2:Int?,
        val colorW3:Int?,
        val colorW4:Int?,
)