package emperatriz.fluviatilis.themes

data class Theme (
        val fluvHeight:Int,
        val fluvNumber: Int,
        val fluvWeight: Int,
        val speed:Int,
        val wideness:Int,
        val heightness:Int,
        val dimAlpha:Int,
        val dimHeight:Int,
        val rotation:Int,
        val horizontalOffset:Int,
        val verticalOffset:Int,
        val color:Int,
        val colorLeft:Int,
        val colorRight:Int,
        val widgetSelected:Int,
        val widgetX:Int?,
        val widgetY:Int?,
        val widgetXsize:Int?,
        val style:Int?,
        val discreto:Boolean?,
        val halo:Boolean?,
        val colorW1:Int?,
        val colorW2:Int?,
        val colorW3:Int?,
        val colorW4:Int?,
)